// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztmoinkpjwuqsarxtavu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0bW9pbmtwand1cXNhcnh0YXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTgwNTgsImV4cCI6MjA2NzA3NDA1OH0.tnHhhkH39D9d1-4AArQkkGBC9sqINeuM820QMSe8_gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});